services:
  api:
    build:
      context: ./app
    command: ["uvicorn", "--host", "0.0.0.0", "--reload", "--factory", "app.main:create_app"]
    env_file:
      - path: .env
        required: false
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8005:8000"
    volumes:
      - ./app:/code/app
    healthcheck:
      test: curl localhost:8000/healthz || exit 1
      timeout: 2s
      interval: 3s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - script.painless.regex.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 4096
      nofile: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1

  seed:
    build:
      context: ./seed_image
      args:
        ES_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started

volumes:
  es_data:
